### ISSUE TITLE
Plan the Waiting List Website Structure

### ISSUE THREAD

**Issue by DevStrike-Codes** [Devstrike-DigTech/FadaWaitingListWeb#8]
- [x] Create a sitemap to outline the website's structure and pages.
- [x] Determine the flow of the registration process.
- [x] Design the user interface and user experience (UI/UX) for easy navigation and interaction.

**Comment by EQua-Dev** [comment]
![Image](https://github.com/Devstrike-DigTech/FadaWaitingListWeb/assets/43550320/12e438cd-af74-466e-95ca-fd3b72e363f3)
